### ISSUE TITLE
HTML Check

### ISSUE THREAD

**Issue by breecousineau** [breecousineau/product-page#1]
Hi @KarenMendozaGarza

I think I know what happened! Here is the right repo! I accidentally made another one last week thinking we had to make it from scratch!

Let me know if you can see my code! Thanks!

Bree

**Comment by KarenMendozaGarza** [comment]
Everything looks right for the most part. Well done here. Only some minor errors that may or may not give you a headache when you start the css. Like this one: make sure you close any divs you open. Also are you plannig on doing something specific to each of those images? if not, they wouldn't need individual classes. If youre doing something to the images in those cards, you should give them all the same class to target in css so its less work for you and its consistant. I also don't think they need to be in a div. 
https://github.com/breecousineau/product-page/blob/5b6ac36c1ff1bdd41d0178c92888116cf042781f/index.html#L92-L97

**Comment by breecousineau** [comment]
Ahh ok I see what you mean. I think I understand. Does this look better?

<img width="729" alt="Screen Shot 2022-10-16 at 9 24 54 PM" src="https://user-images.githubusercontent.com/97452245/196070224-4a4f1e6b-ba41-42d2-a348-e5479cb72c5e.png">

**Comment by KarenMendozaGarza** [comment]
Not quite. You want to keep the cards in their own divs so you can sort them with flex and grid without disrupting the content inside. So you had it right before. You just had a starting div before every image (line 93 in my last message) that didn't close and had a specific class belonging to each image. That's the ones I was talking about. Sorry if it wasn't super clear!

**Comment by breecousineau** [comment]
oh I see ok hopefully I understood it! Let me know if you can see my changes

Thank you again!

**Comment by breecousineau** [comment]
Hi @KarenMendozaGarza

Sorry for bothering you, just whenever you get a second do you mind looking at my css? I'm going to reach out to Wendy to go over media queries again with me because mine's a hot mess and I'm not understanding it :(

**Comment by KarenMendozaGarza** [comment]
Hey bree, I'm not seeing much in your css for the media query. Have you pushed up recently?

**Comment by KarenMendozaGarza** [comment]
This is all i have on my end. Does that look right?

<img width="635" alt="Screen Shot 2022-10-18 at 10 19 44 PM" src="https://user-images.githubusercontent.com/77505891/196581939-36c294aa-7728-4589-aa4e-f288ef5e4fe7.png">
